# Generated by Django 2.0.2 on 2019-06-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iitjuser',
            name='age',
        ),
        migrations.AddField(
            model_name='iitjuser',
            name='hostel',
            field=models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('G5', 'G5'), ('G6', 'G6')], default='green', max_length=6),
        ),
    ]
