# Generated by Django 2.0.2 on 2019-06-28 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190624_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('number_of_members_required', models.IntegerField()),
                ('status', models.CharField(choices=[('ONGOING', 'ongoing'), ('COMPLETED', 'completed')], default='ongoing', max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
