# Generated by Django 2.0.2 on 2019-07-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20190718_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuematerial',
            name='provided',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
