# Generated by Django 2.0.2 on 2019-07-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_issuematerial_provided'),
    ]

    operations = [
        migrations.CreateModel(
            name='MustKnowPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
            ],
        ),
    ]
