# Generated by Django 2.0.2 on 2019-07-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_mustknowpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='mustknowpeople',
            name='image1',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
